/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Q2 */

#ifndef _Included_Q2
#define _Included_Q2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Q2
 * Method:    sayHello
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Q2_sayHello
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
